In [10]:
import pandas as pd

path = "C:\\Users\\FIC\\Documents\\david_python\\"
file_a = 'nba_2015_a.csv'

df_a = pd.read_csv (path + file_a)

df_a.head()

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player
0,Karl-Anthony Towns,C,karl-anthony-towns,2015,1.030606,0.134767,0.427183,0.163083
1,Justise Winslow,SF,justise-winslow,2015,0.875329,0.083529,0.510905,0.176767
2,Stanley Johnson,SF,stanley-johnson,2015,0.679493,0.067800,0.423733,0.278500
3,Jahlil Okafor,C,jahlil-okafor,2015,0.521661,0.058717,0.409900,0.235533
4,D`Angelo Russell,PG,d-angelo-russell,2015,0.511967,0.152033,0.342283,0.096583

In [11]:
file_b ='nba_2015_b.csv'

df_b = pd.read_csv(path + file_b)

df_b.head()

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player
0,Austin Rivers,SG,austin-rivers,2012,-0.145824,0.036233,0.268867,0.334098
1,Royce White,SF,royce-white,2012,-0.193490,0.018400,0.243750,0.357367
2,Damian Lillard,PG,damian-lillard,2012,-0.200562,0.036314,0.259300,0.273522
3,Tony Wroten,PG,tony-wroten,2012,-0.245215,0.021567,0.280567,0.286900
4,Doron Lamb,SG,doron-lamb,2012,-0.281442,0.004280,0.208319,0.439637